version: '3.8'

services:
  app:
    build: .
    working_dir: /workspace
    volumes:
      - .:/workspace
    depends_on:
      - db
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    command: sleep infinity

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-family_knowledge}
      POSTGRES_USER: ${DB_USER:-family_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-family_dev_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-family_user} -d ${DB_NAME:-family_knowledge}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: